# Generated by Django 5.0.7 on 2024-08-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('israeli_id', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('birthdate', models.DateField(null=True)),
                ('guardian_phone_number', models.CharField(blank=True, default='', max_length=10)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=30)),
                ('gender', models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], max_length=10)),
                ('is_having_regular_menstruation', models.BooleanField(blank=True, default=True)),
                ('is_on_cocp', models.BooleanField(blank=True, default=False)),
                ('front_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.OneToOneField>>/questionnaire/')),
                ('side_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.OneToOneField>>/questionnaire/')),
                ('back_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.OneToOneField>>/questionnaire/')),
                ('daily_routine', models.TextField()),
                ('daily_diet', models.TextField()),
                ('unliked_sauce', models.CharField(blank=True, default='', max_length=50)),
                ('alergies', models.CharField(blank=True, default='', max_length=50)),
                ('supplements', models.CharField(blank=True, default='', max_length=50)),
                ('liked_food', models.TextField(blank=True, default='')),
                ('num_of_meals', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('is_drinking_soda', models.BooleanField(default=False)),
                ('which_soda', models.TextField(blank=True, default='')),
                ('liked_sauce', models.CharField(blank=True, default='', max_length=50)),
                ('is_able_to_weight_food', models.BooleanField(default=False)),
                ('is_drinking_alcohol', models.BooleanField(default=False)),
                ('which_alcohol', models.TextField(blank=True, default='')),
                ('was_under_thousand_calories_diet', models.BooleanField(default=False)),
                ('thousand_calorie_diet', models.TextField(blank=True, default='')),
                ('current_training', models.TextField(blank=True, default='')),
                ('current_training_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.OneToOneField>>/current_training/')),
                ('weekly_aerobic', models.TextField(blank=True, default='')),
                ('unliked_exercises', models.TextField(blank=True, default='')),
                ('commit_training_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('former_injuries', models.TextField(blank=True, default='')),
                ('further_info', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.FileField(blank=True, default='default/default-user.jpg', null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.OneToOneField>>/profile_picture/')),
                ('has_filled_questionnaire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('תפריט', 'תפריט'), ('אימונים', 'אימונים'), ('מידע', 'מידע')], default='מידע', max_length=50)),
                ('is_watched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.CharField(default='', max_length=10)),
                ('is_done_all_aerobic_exer', models.BooleanField(default=False)),
                ('missing_aerobic', models.TextField(blank=True, default='')),
                ('is_done_all_training_exer', models.BooleanField(default=False)),
                ('missing_training', models.TextField(blank=True, default='')),
                ('level_of_diet_fulfillment', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=10)),
                ('protein_intake', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=10)),
                ('carb_intake', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=10)),
                ('fat_intake', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=10)),
                ('water_intake', models.TextField(default='')),
                ('avg_sleep_hours', models.CharField(default='', max_length=10)),
                ('further_info', models.TextField(default='')),
                ('front_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>/update_history/<django.db.models.fields.DateTimeField>/')),
                ('side_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>/update_history/<django.db.models.fields.DateTimeField>/')),
                ('back_image', models.FileField(blank=True, null=True, upload_to='images/<bound method Field.__str__ of <django.db.models.fields.related.ForeignKey>>/update_history/<django.db.models.fields.DateTimeField>/')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
