# Generated by Django 5.0.7 on 2024-07-31 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=30, null=True)),
                ('israeli_id', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('guardian_phone_number', models.CharField(blank=True, default='', max_length=10)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=30)),
                ('gender', models.CharField(choices=[('זכר', 'זכר'), ('נקבה', 'נקבה')], max_length=10)),
                ('is_having_regular_menstruation', models.BooleanField(blank=True, default=True)),
                ('is_on_cocp', models.BooleanField(blank=True, default=False)),
                ('daily_routine', models.TextField()),
                ('daily_diet', models.TextField()),
                ('unliked_sauce', models.CharField(blank=True, default='', max_length=50)),
                ('alergies', models.CharField(blank=True, default='', max_length=50)),
                ('supplements', models.CharField(blank=True, default='', max_length=50)),
                ('liked_food', models.TextField(blank=True, default='')),
                ('num_of_meals', models.CharField(choices=[('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('is_drinking_soda', models.BooleanField(default=False)),
                ('which_soda', models.TextField(blank=True, default='')),
                ('liked_sauce', models.CharField(blank=True, default='', max_length=50)),
                ('is_able_to_weight_food', models.BooleanField(default=False)),
                ('is_drinking_alcohol', models.BooleanField(default=False)),
                ('which_alcohol', models.TextField(blank=True, default='')),
                ('was_under_thousand_calories_diet', models.BooleanField(default=False)),
                ('thousand_calorie_diet', models.TextField(blank=True, default='')),
                ('current_training', models.TextField(blank=True, default='')),
                ('weekly_aerobic', models.TextField(blank=True, default='')),
                ('unliked_exercises', models.TextField(blank=True, default='')),
                ('commit_training_number', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10)),
                ('former_injuries', models.TextField(blank=True, default='')),
                ('further_info', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_filled_questionnaire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_data', to='api.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
