# Generated by Django 5.0.7 on 2024-07-29 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=30)),
                ('israeli_id', models.CharField(max_length=9, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('guardian_phone_number', models.CharField(max_length=10)),
                ('guardian_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('is_having_regular_menstruation', models.BooleanField(default=True)),
                ('is_on_cocp', models.BooleanField(default=False)),
                ('daily_routine', models.TextField()),
                ('daily_diet', models.TextField()),
                ('unliked_sauce', models.CharField(max_length=50)),
                ('alergies', models.CharField(max_length=50)),
                ('supplements', models.CharField(max_length=50)),
                ('liked_food', models.TextField()),
                ('num_of_meals', models.CharField(max_length=10)),
                ('is_drinking_soda', models.BooleanField(default=False)),
                ('which_soda', models.TextField()),
                ('liked_sauce', models.CharField(max_length=50)),
                ('is_able_to_weight_food', models.BooleanField(default=False)),
                ('is_drinking_alcohol', models.BooleanField(default=False)),
                ('which_alcohol', models.TextField()),
                ('was_under_thousand_calories_diet', models.BooleanField(default=False)),
                ('thousand_calorie_diet', models.TextField()),
                ('current_training', models.TextField()),
                ('weekly_aerobic', models.TextField()),
                ('unliked_exercises', models.TextField()),
                ('commit_training_number', models.CharField(max_length=10)),
                ('former_injuries', models.TextField()),
                ('further_info', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_filled_questionnaire', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_history', to='api.userdata')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
