# Generated by Django 5.0.7 on 2024-08-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='birthdate',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
