# Generated by Django 5.0.7 on 2024-08-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_birthdate_userdata_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='back_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.OneToOneField>/questionnaire/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='current_training_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.OneToOneField>/current_training/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='front_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.OneToOneField>/questionnaire/'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='side_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.OneToOneField>/questionnaire/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.FileField(blank=True, default='default/default-user.jpg', null=True, upload_to='images/<django.db.models.fields.related.OneToOneField>/profile_picture/'),
        ),
        migrations.AlterField(
            model_name='userupdatehistory',
            name='back_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/update_history/<django.db.models.fields.DateTimeField>/'),
        ),
        migrations.AlterField(
            model_name='userupdatehistory',
            name='front_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/update_history/<django.db.models.fields.DateTimeField>/'),
        ),
        migrations.AlterField(
            model_name='userupdatehistory',
            name='side_image',
            field=models.FileField(blank=True, null=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/update_history/<django.db.models.fields.DateTimeField>/'),
        ),
    ]
