# Generated by Django 5.0.7 on 2024-08-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_userdata_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_training_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/current_training/'),
        ),
    ]
