# Generated by Django 5.0.7 on 2024-08-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userdata_current_training_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='current_training_image',
            field=models.FileField(blank=True, null=True, upload_to='images/current_training/'),
        ),
    ]
