# Generated by Django 5.0.7 on 2024-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userdata_current_training_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='israeli_id',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
