# Generated by Django 5.0.7 on 2024-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userdata_israeli_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='israeli_id',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
    ]
