# Generated by Django 5.0.7 on 2024-08-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userdata_israeli_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupdatehistory',
            name='carb_intake',
            field=models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9.5', '9.5'), ('10', '10')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userupdatehistory',
            name='fat_intake',
            field=models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9.5', '9.5'), ('10', '10')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userupdatehistory',
            name='protein_intake',
            field=models.CharField(choices=[('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9.5', '9.5'), ('10', '10')], default='', max_length=10),
        ),
    ]
